"""Install, remove, or inspect a launchd job that polls `list --warn` and posts macOS notifications."""
from __future__ import annotations

import math
import os
from pathlib import Path
import plistlib
import shlex
import shutil
import subprocess
import sys

LABEL = "com.intellieffect.xswap.alert"


class AlertError(Exception):
    pass


# The run.sh template below is filled in with str.replace() rather than str.format()
# or string.Template, because the script itself is full of shell "$var" references
# and "{ ... }" grouping that would otherwise collide with a formatting mini-language.
#
# __XSWAP_ALERT_LOG__ and __XSWAP_ALERT_BIN__ are install-time, filesystem-derived paths
# (CODEX_SWAP_HOME, the resolved xswap binary) that an attacker who controls the
# environment could shape to contain shell metacharacters. render_run_script() below
# substitutes them pre-quoted with shlex.quote() so they land in the script as inert
# single-quoted literals; never substitute a raw path into this template directly.
RUN_SCRIPT_TEMPLATE = r"""#!/bin/sh
# Generated by `xswap alert --install`. Re-run that command to regenerate; do not hand-edit.
set -u
umask 077

LOG=__XSWAP_ALERT_LOG__
STDERR_TMP="$LOG.stderr.tmp"

: > "$LOG"

if command -v timeout >/dev/null 2>&1; then
  RUNNER="timeout 120"
elif command -v gtimeout >/dev/null 2>&1; then
  RUNNER="gtimeout 120"
else
  RUNNER=""
fi

$RUNNER __XSWAP_ALERT_BIN__ list --warn __XSWAP_ALERT_WARN__ --cached __XSWAP_ALERT_CACHED__ >>"$LOG" 2>"$STDERR_TMP"
status=$?

{
  printf '%s xswap list exited %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$status"
  cat "$STDERR_TMP" 2>/dev/null
} >>"$LOG"

if [ "$status" -eq 3 ]; then
  while IFS= read -r line; do
    case "$line" in
      warn:*)
        msg=${line#warn: }
        # Escape backslashes first, then double quotes, so the message survives as an
        # AppleScript string literal no matter what characters a warn: line contains.
        esc=$(printf '%s' "$msg" | sed 's/\\/\\\\/g; s/"/\\"/g')
        osascript -e "display notification \"$esc\" with title \"xswap\"" >>"$LOG" 2>&1
        ;;
    esac
  done < "$STDERR_TMP"
fi

rm -f "$STDERR_TMP"
exit 0
"""


def alert_dir(root):
    return Path(root) / "alert"


def run_script_path(root):
    return alert_dir(root) / "run.sh"


def log_path(root):
    return alert_dir(root) / "last.log"


def plist_path():
    return Path.home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"


def resolve_xswap():
    """Absolute path to the xswap executable at install time.

    launchd's PATH does not include /opt/homebrew/bin, so the wrapper must call an
    absolute path rather than relying on `xswap` being found again at run time.
    """
    found = shutil.which("xswap")
    if found:
        return str(Path(found).resolve())
    argv0 = Path(sys.argv[0])
    if argv0.name == "xswap":
        return str(argv0.resolve())
    raise AlertError(
        "Could not find an `xswap` executable on PATH to bake into the wrapper script. "
        "Install xswap so it is on PATH (e.g. `uv tool install .` or `pip install .`), then retry."
    )


def format_number(value):
    return f"{float(value):g}"


def validate_warn(value):
    try:
        value = float(value)
    except (TypeError, ValueError):
        raise AlertError("--warn must be a number from 1 to 100.") from None
    if not math.isfinite(value) or not 1 <= value <= 100:
        raise AlertError("--warn must be a number from 1 to 100.")
    return value


def validate_every(value):
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        raise AlertError("--every must be a whole number of minutes, at least 1.") from None
    if not math.isfinite(numeric) or numeric < 1 or numeric != int(numeric):
        raise AlertError("--every must be a whole number of minutes, at least 1 "
                          "(launchd merges shorter intervals into 60s anyway; fractional minutes "
                          "cannot be expressed in the crontab fallback either).")
    return int(numeric)


def validate_cached(value):
    try:
        value = float(value)
    except (TypeError, ValueError):
        raise AlertError("--cached must be zero or a positive number of seconds.") from None
    if not math.isfinite(value) or value < 0:
        raise AlertError("--cached must be zero or a positive number of seconds.")
    return value


def render_run_script(xswap_path, warn, cached, log):
    # xswap_path and log are filesystem paths outside this function's control (the resolved
    # xswap binary, and a path derived from CODEX_SWAP_HOME); shlex.quote() wraps each in
    # POSIX single quotes (escaping any embedded single quote as '\''), so `$(...)`,
    # backticks, spaces, and quotes inside them are inert literal text to the shell that
    # later parses this script, not live syntax. Never substitute either value unquoted.
    script = RUN_SCRIPT_TEMPLATE
    script = script.replace("__XSWAP_ALERT_LOG__", shlex.quote(str(log)))
    script = script.replace("__XSWAP_ALERT_BIN__", shlex.quote(str(xswap_path)))
    script = script.replace("__XSWAP_ALERT_WARN__", format_number(warn))
    script = script.replace("__XSWAP_ALERT_CACHED__", format_number(cached))
    return script


def build_plist(xswap_path, every, script_path, out_path, err_path):
    xswap_dir = str(Path(xswap_path).parent)
    path_entries = [xswap_dir, "/opt/homebrew/bin", "/usr/local/bin", "/usr/bin", "/bin"]
    return {
        "Label": LABEL,
        "ProgramArguments": [str(script_path)],
        "StartInterval": int(every * 60),
        "RunAtLoad": False,
        "StandardOutPath": str(out_path),
        "StandardErrorPath": str(err_path),
        "EnvironmentVariables": {"PATH": ":".join(path_entries)},
    }


def _private_dir(path):
    path.mkdir(parents=True, exist_ok=True, mode=0o700)
    if path.is_symlink() or path.stat().st_uid != os.getuid():
        raise AlertError(f"Unsafe alert directory: {path}")
    path.chmod(0o700)


def _bootstrap_target():
    return f"gui/{os.getuid()}/{LABEL}"


def _print_cron_equivalent(warn, every, cached):
    # `every` is already a validated whole number of minutes (validate_every), so this
    # matches the plist's StartInterval = every * 60 exactly, with no silent truncation.
    print("xswap alert manages launchd, which is macOS-only. Use a crontab entry instead:")
    print(f"*/{every} * * * * {resolve_xswap()} list --warn {format_number(warn)} --cached {format_number(cached)}")
    return 2


def install(root, *, warn=15, every=30, cached=600, dry_run=False):
    warn = validate_warn(warn)
    every = validate_every(every)
    cached = validate_cached(cached)

    if sys.platform != "darwin":
        return _print_cron_equivalent(warn, every, cached)

    xswap_path = resolve_xswap()
    a_dir = alert_dir(root)
    script_path = run_script_path(root)
    log = log_path(root)
    plist = plist_path()
    plist_data = build_plist(xswap_path, every, script_path, a_dir / "launchd.out.log", a_dir / "launchd.err.log")

    if dry_run:
        print(f"Would write {script_path}")
        print(f"Would write {plist}")
        print(f"Would run: launchctl bootstrap gui/{os.getuid()} {plist}")
        return 0

    _private_dir(a_dir)
    script_path.write_text(render_run_script(xswap_path, warn, cached, log))
    script_path.chmod(0o700)

    plist.parent.mkdir(parents=True, exist_ok=True)
    plist.write_bytes(plistlib.dumps(plist_data))

    target = _bootstrap_target()
    already_loaded = subprocess.run(["launchctl", "print", target], capture_output=True, text=True)
    if already_loaded.returncode == 0:
        bootout_cmd = ["launchctl", "bootout", target]
        print(" ".join(bootout_cmd))
        subprocess.run(bootout_cmd, capture_output=True, text=True)

    bootstrap_cmd = ["launchctl", "bootstrap", f"gui/{os.getuid()}", str(plist)]
    print(" ".join(bootstrap_cmd))
    result = subprocess.run(bootstrap_cmd, capture_output=True, text=True)
    if result.returncode != 0:
        detail = (result.stderr or result.stdout or "").strip()
        raise AlertError(f"launchctl bootstrap failed: {detail}" if detail else "launchctl bootstrap failed.")

    print(f"Installed {plist}")
    print(f"Wrapper: {script_path}")
    print(f"Log: {log}")
    return 0


def uninstall(root, *, dry_run=False):
    if sys.platform != "darwin":
        print("xswap alert manages launchd, which is macOS-only; nothing was installed here. Remove your crontab entry manually.")
        return 2

    plist = plist_path()
    a_dir = alert_dir(root)
    target = _bootstrap_target()

    if dry_run:
        print(f"Would run: launchctl bootout {target}")
        print(f"Would delete {plist}")
        print(f"Would delete {a_dir}")
        return 0

    bootout_cmd = ["launchctl", "bootout", target]
    print(" ".join(bootout_cmd))
    subprocess.run(bootout_cmd, capture_output=True, text=True)  # "not loaded" and similar failures are expected and ignored

    if plist.exists():
        plist.unlink()
    if a_dir.exists():
        shutil.rmtree(a_dir)
    print(f"Removed {plist} and {a_dir}.")
    return 0


def status(root):
    if sys.platform != "darwin":
        print("xswap alert manages launchd, which is macOS-only; nothing is installed here.")
        return 2

    plist = plist_path()
    exists = plist.exists()
    target = _bootstrap_target()
    loaded = False
    if exists:
        result = subprocess.run(["launchctl", "print", target], capture_output=True, text=True)
        loaded = result.returncode == 0

    print(f"plist: {'present' if exists else 'absent'} ({plist})")
    print(f"loaded: {'yes' if loaded else 'no'} ({target})")

    log = log_path(root)
    if log.exists():
        print("last.log (last 10 lines):")
        for line in log.read_text(errors="replace").splitlines()[-10:]:
            print(f"  {line}")
    else:
        print(f"last.log: none yet ({log})")
    return 0
